### ISSUE TITLE
Inversion in DistinctionsForCollectionsWithDifferentLength

### ISSUE THREAD

**Issue by nvannier-cpi-france** [valeraf23/ObjectComparator#14]
Hello,

I think that the Distinction created by this function is with inverted parameters -> "first" and "second" should be swapped as this :
`DeepEqualityResult.Create(new Distinction($"Property \"{propertyName}\": Collection has different length", $"{first}", $"{second}"));
`
Except this bug, ObjectComparator is really functioning very well 👍

Thanks

**Comment by valeraf23** [comment]
Hello @nvannier-cpi-france ,

Thank you for reporting the issue.

The fix has been rolled out in the ObjectComparator version 3.5.7 package.

I appreciate your feedback and are pleased to hear that you find ObjectComparator very useful.
